// <auto-generated />
namespace _33.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    //public sealed partial class InitialCreate : IMigrationMetadata
    //{
    //    private readonly ResourceManager Resources = new ResourceManager(typeof(InitialCreate));
        
    //    string IMigrationMetadata.Id
    //    {
    //        get { return "201306181255220_InitialCreate"; }
    //    }
        
    //    string IMigrationMetadata.Source
    //    {
    //        get { return null; }
    //    }
        
    //    string IMigrationMetadata.Target
    //    {
    //        get { return Resources.GetString("Target"); }
    //    }
    //}
}
