// <auto-generated />
namespace _33.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class homeModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(homeModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201308081212408_homeModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
