window.MALL_DATA = {
  floors: [
    { id: 1, name: "Level 1 · Beauty & Jewels", vibe: "Glowy counters, soft perfume, rose-gold light" },
    { id: 2, name: "Level 2 · Haute Fashion", vibe: "Marble floors, velvet sofas, runway sparkle" },
    { id: 3, name: "Level 3 · Sport & Icons", vibe: "Sneaker walls, soft lounge music, neon blush" },
  ],

  stores: [
    // Level 1 — beauty & jewels (fancy)
    {
      id: "sephora",
      name: "Sephora",
      floor: 1,
      fancy: true,
      color: "#E91E63",
      blurb: "Makeup playground with endless glow.",
      cashier: "Welcome to Sephora, gorgeous! Ready to check out that glam?",
      items: [
        { id: "sep-palette", name: "Rose Nude Palette", slot: "accessory", price: 52, swatch: "#F4A7B9", shape: "square" },
        { id: "sep-gloss", name: "Cherry Gloss", slot: "accessory", price: 24, swatch: "#FF4D6D", shape: "circle" },
        { id: "sep-highlighter", name: "Pearl Highlighter", slot: "accessory", price: 38, swatch: "#FFE8F0", shape: "diamond" },
        { id: "sep-brush", name: "Pink Brush Set", slot: "accessory", price: 45, swatch: "#FFC0D9", shape: "square" },
        { id: "sep-perfume", name: "Cloud Perfume Mini", slot: "accessory", price: 68, swatch: "#E7D5FF", shape: "circle" },
      ],
    },
    {
      id: "chanel",
      name: "Chanel",
      floor: 1,
      fancy: true,
      color: "#1a1a1a",
      blurb: "Timeless couture beauty and little black chic.",
      cashier: "Bonjour. Shall I wrap your Chanel selections?",
      items: [
        { id: "cha-bag", name: "Classic Flap Mini", slot: "bag", price: 5800, swatch: "#111111", shape: "square" },
        { id: "cha-lipstick", name: "Rouge Coco Lip", slot: "accessory", price: 50, swatch: "#B01030", shape: "circle" },
        { id: "cha-jacket", name: "Tweed Jacket", slot: "top", price: 4200, swatch: "#F2D7E0", shape: "square" },
        { id: "cha-pumps", name: "Two-Tone Pumps", slot: "shoes", price: 1100, swatch: "#F5F0EB", shape: "diamond" },
      ],
    },
    {
      id: "dior",
      name: "Dior",
      floor: 1,
      fancy: true,
      color: "#6B0F2B",
      blurb: "Couture beauty and soft luxury layers.",
      cashier: "Welcome to Dior. Let’s make this purchase divine.",
      items: [
        { id: "dio-saddle", name: "Saddle Bag", slot: "bag", price: 3900, swatch: "#C7A27C", shape: "square" },
        { id: "dio-blush", name: "Rosy Glow Blush", slot: "accessory", price: 48, swatch: "#FF8FAB", shape: "circle" },
        { id: "dio-dress", name: "Bar Jacket Dress", slot: "top", price: 3200, swatch: "#F7E7EF", shape: "diamond" },
        { id: "dio-heels", name: "J’adior Heels", slot: "shoes", price: 990, swatch: "#FFFFFF", shape: "circle" },
      ],
    },
    {
      id: "tiffany",
      name: "Tiffany & Co.",
      floor: 1,
      fancy: true,
      color: "#81D8D0",
      blurb: "Blue-box sparkle and delicate jewels.",
      cashier: "Something blue and brilliant today?",
      items: [
        { id: "tif-necklace", name: "Heart Tag Necklace", slot: "accessory", price: 425, swatch: "#B8F2EC", shape: "diamond" },
        { id: "tif-ring", name: "Return to Tiffany Ring", slot: "accessory", price: 375, swatch: "#E8FFFC", shape: "circle" },
        { id: "tif-bracelet", name: "T Smile Bracelet", slot: "accessory", price: 650, swatch: "#9FE7DF", shape: "square" },
        { id: "tif-earrings", name: "Diamond Studs", slot: "accessory", price: 1800, swatch: "#FFFFFF", shape: "diamond" },
      ],
    },
    {
      id: "cartier",
      name: "Cartier",
      floor: 1,
      fancy: true,
      color: "#B11226",
      blurb: "Iconic red-box jewels and love bracelets.",
      cashier: "A Cartier moment — shall I gift-wrap it?",
      items: [
        { id: "car-love", name: "Love Bracelet", slot: "accessory", price: 6900, swatch: "#D4AF37", shape: "circle" },
        { id: "car-watch", name: "Tank Watch", slot: "accessory", price: 3400, swatch: "#F5E6C8", shape: "square" },
        { id: "car-panthere", name: "Panthère Ring", slot: "accessory", price: 5200, swatch: "#E8C872", shape: "diamond" },
        { id: "car-nails", name: "Juste un Clou", slot: "accessory", price: 4100, swatch: "#C9A227", shape: "square" },
      ],
    },
    {
      id: "ysl",
      name: "Yves Saint Laurent",
      floor: 1,
      fancy: true,
      color: "#2B0A0A",
      blurb: "Bold beauty and sleek Parisian edges.",
      cashier: "YSL counter is ready whenever you are.",
      items: [
        { id: "ysl-bag", name: "Lou Camera Bag", slot: "bag", price: 1790, swatch: "#4A0E0E", shape: "square" },
        { id: "ysl-lipstick", name: "Rouge Pur Couture", slot: "accessory", price: 42, swatch: "#8B0000", shape: "circle" },
        { id: "ysl-blazer", name: "Le Smoking Blazer", slot: "top", price: 2600, swatch: "#1C1C1C", shape: "square" },
        { id: "ysl-boots", name: "Opyum Boots", slot: "shoes", price: 1290, swatch: "#2A0A0A", shape: "diamond" },
      ],
    },
    {
      id: "apple",
      name: "Apple",
      floor: 1,
      fancy: false,
      color: "#A2AAAD",
      blurb: "Glassy gadgets with soft pink cases.",
      cashier: "Hi! Want me to ring those up with AppleCare vibes?",
      items: [
        { id: "app-iphone", name: "iPhone Pink Case", slot: "accessory", price: 49, swatch: "#FFB6C1", shape: "square" },
        { id: "app-airpods", name: "AirPods Max Pink", slot: "accessory", price: 549, swatch: "#F8C8DC", shape: "circle" },
        { id: "app-watch", name: "Watch Soft Rose Band", slot: "accessory", price: 249, swatch: "#E8A0BF", shape: "diamond" },
        { id: "app-wallet", name: "MagSafe Wallet", slot: "accessory", price: 59, swatch: "#F5D0E0", shape: "square" },
      ],
    },

    // Level 2 — haute fashion
    {
      id: "zara",
      name: "Zara",
      floor: 2,
      fancy: false,
      color: "#111111",
      blurb: "Trend pieces with clean chic energy.",
      cashier: "Zara till is open — want these in a bag?",
      items: [
        { id: "zar-blazer", name: "Satin Blazer", slot: "top", price: 89, swatch: "#F3C4D8", shape: "square" },
        { id: "zar-skirt", name: "Pleated Midi Skirt", slot: "bottom", price: 59, swatch: "#FFFFFF", shape: "diamond" },
        { id: "zar-heels", name: "Strappy Heels", slot: "shoes", price: 69, swatch: "#FFCAD4", shape: "circle" },
        { id: "zar-bag", name: "Mini City Bag", slot: "bag", price: 49, swatch: "#EAD7C4", shape: "square" },
        { id: "zar-top", name: "Bow Knit Top", slot: "top", price: 39, swatch: "#FFDEE9", shape: "circle" },
      ],
    },
    {
      id: "gucci",
      name: "Gucci",
      floor: 2,
      fancy: true,
      color: "#0B6623",
      blurb: "Maximal logos, soft florals, runway drama.",
      cashier: "Gucci boutique checkout — fabulous choice.",
      items: [
        { id: "guc-bag", name: "GG Marmont Bag", slot: "bag", price: 2500, swatch: "#5C4033", shape: "square" },
        { id: "guc-hoodie", name: "Logo Hoodie", slot: "top", price: 1200, swatch: "#F7C6D0", shape: "square" },
        { id: "guc-slides", name: "Horsebit Slides", slot: "shoes", price: 650, swatch: "#D8B4A0", shape: "diamond" },
        { id: "guc-scarf", name: "Floral Silk Scarf", slot: "accessory", price: 495, swatch: "#FF9EBB", shape: "circle" },
      ],
    },
    {
      id: "lv",
      name: "Louis Vuitton",
      floor: 2,
      fancy: true,
      color: "#8B5E3C",
      blurb: "Monogram dreams and trunk-house polish.",
      cashier: "Welcome to Louis Vuitton. Shall I prepare a bag?",
      items: [
        { id: "lv-neverfull", name: "Neverfull MM", slot: "bag", price: 2100, swatch: "#C2A67E", shape: "square" },
        { id: "lv-speedy", name: "Speedy Bandoulière", slot: "bag", price: 1840, swatch: "#A67C52", shape: "square" },
        { id: "lv-scarf", name: "Silk Bandeau", slot: "accessory", price: 250, swatch: "#F4C2C2", shape: "circle" },
        { id: "lv-sneakers", name: "Trainer Sneakers", slot: "shoes", price: 990, swatch: "#FFFFFF", shape: "diamond" },
      ],
    },
    {
      id: "prada",
      name: "Prada",
      floor: 2,
      fancy: true,
      color: "#000000",
      blurb: "Minimal black, nylon icons, sharp lines.",
      cashier: "Prada desk — elegant selections.",
      items: [
        { id: "pra-reedition", name: "Re-Edition Bag", slot: "bag", price: 1450, swatch: "#222222", shape: "square" },
        { id: "pra-nylon", name: "Nylon Jacket", slot: "top", price: 1680, swatch: "#1A1A1A", shape: "square" },
        { id: "pra-loafers", name: "Chocolate Loafers", slot: "shoes", price: 980, swatch: "#5C4033", shape: "diamond" },
        { id: "pra-skirt", name: "Pleated Techno Skirt", slot: "bottom", price: 1200, swatch: "#2C2C2C", shape: "circle" },
      ],
    },
    {
      id: "hermes",
      name: "Hermès",
      floor: 2,
      fancy: true,
      color: "#F37021",
      blurb: "Orange-box luxury and silk daydreams.",
      cashier: "Hermès welcomes you. Ready for your orange box?",
      items: [
        { id: "her-birkin", name: "Birkin Inspired Tote", slot: "bag", price: 12000, swatch: "#C68642", shape: "square" },
        { id: "her-scarf", name: "Carré Silk Scarf", slot: "accessory", price: 480, swatch: "#FF8C42", shape: "diamond" },
        { id: "her-bracelet", name: "Clic H Bracelet", slot: "accessory", price: 740, swatch: "#F7D6E0", shape: "circle" },
        { id: "her-sandals", name: "Oran Sandals", slot: "shoes", price: 780, swatch: "#E8B4BC", shape: "square" },
      ],
    },
    {
      id: "balenciaga",
      name: "Balenciaga",
      floor: 2,
      fancy: true,
      color: "#111111",
      blurb: "Oversized cool with couture attitude.",
      cashier: "Balenciaga checkout. Let’s bag the drama.",
      items: [
        { id: "bal-hoodie", name: "Oversized Hoodie", slot: "top", price: 950, swatch: "#F5C6D0", shape: "square" },
        { id: "bal-triple", name: "Triple S Sneakers", slot: "shoes", price: 995, swatch: "#F0E6EE", shape: "circle" },
        { id: "bal-bag", name: "Hourglass Bag", slot: "bag", price: 2250, swatch: "#2B2B2B", shape: "diamond" },
        { id: "bal-cap", name: "Logo Cap", slot: "accessory", price: 450, swatch: "#FFFFFF", shape: "square" },
      ],
    },
    {
      id: "fendi",
      name: "Fendi",
      floor: 2,
      fancy: true,
      color: "#C9A227",
      blurb: "FF logos, soft yellows, Italian glam.",
      cashier: "Ciao! Fendi is ready to wrap your picks.",
      items: [
        { id: "fen-baguette", name: "Baguette Bag", slot: "bag", price: 3200, swatch: "#E8D5A3", shape: "square" },
        { id: "fen-sunglasses", name: "FF Sunglasses", slot: "accessory", price: 490, swatch: "#F5E6C5", shape: "diamond" },
        { id: "fen-knit", name: "Logo Knit Top", slot: "top", price: 980, swatch: "#FFF0F5", shape: "circle" },
        { id: "fen-boots", name: "First Boots", slot: "shoes", price: 1250, swatch: "#3B2F2F", shape: "square" },
      ],
    },

    // Level 3 — sport & icons
    {
      id: "nike",
      name: "Nike",
      floor: 3,
      fancy: false,
      color: "#111111",
      blurb: "Sneakers and sporty-soft sets.",
      cashier: "Just do it — want these boxed up?",
      items: [
        { id: "nik-dunk", name: "Dunk Low Pink", slot: "shoes", price: 115, swatch: "#FFB6C1", shape: "circle" },
        { id: "nik-set", name: "Tech Fleece Set Top", slot: "top", price: 120, swatch: "#F8D7E5", shape: "square" },
        { id: "nik-shorts", name: "Sport Shorts", slot: "bottom", price: 45, swatch: "#FFFFFF", shape: "diamond" },
        { id: "nik-bag", name: "Gym Tote", slot: "bag", price: 55, swatch: "#FFC0CB", shape: "square" },
      ],
    },
    {
      id: "adidas",
      name: "Adidas",
      floor: 3,
      fancy: false,
      color: "#000000",
      blurb: "Three stripes with soft pastel energy.",
      cashier: "Adidas register — great picks!",
      items: [
        { id: "adi-samba", name: "Samba OG", slot: "shoes", price: 100, swatch: "#F5F5F5", shape: "circle" },
        { id: "adi-track", name: "Track Jacket", slot: "top", price: 90, swatch: "#F3C1D4", shape: "square" },
        { id: "adi-pants", name: "Firebird Pants", slot: "bottom", price: 80, swatch: "#2A2A2A", shape: "diamond" },
        { id: "adi-bag", name: "Mini Airliner Bag", slot: "bag", price: 70, swatch: "#E8B4BC", shape: "square" },
      ],
    },
    {
      id: "lululemon",
      name: "Lululemon",
      floor: 3,
      fancy: true,
      color: "#D31345",
      blurb: "Buttery soft sets for pretty errands.",
      cashier: "Need a bag for your Align vibes?",
      items: [
        { id: "lulu-align", name: "Align Leggings", slot: "bottom", price: 98, swatch: "#F4C2C2", shape: "square" },
        { id: "lulu-define", name: "Define Jacket", slot: "top", price: 128, swatch: "#FFE4EC", shape: "diamond" },
        { id: "lulu-belt", name: "Everywhere Belt Bag", slot: "bag", price: 38, swatch: "#E8A0BF", shape: "circle" },
        { id: "lulu-scuba", name: "Scuba Hoodie", slot: "top", price: 118, swatch: "#F7D6E0", shape: "square" },
      ],
    },
    {
      id: "vs",
      name: "Victoria's Secret",
      floor: 3,
      fancy: true,
      color: "#6B0F2B",
      blurb: "Soft glam loungewear and sparkle wings energy.",
      cashier: "Hi angel — ready to check out?",
      items: [
        { id: "vs-robe", name: "Satin Robe", slot: "top", price: 79, swatch: "#E8B4BC", shape: "diamond" },
        { id: "vs-slippers", name: "Feather Slippers", slot: "shoes", price: 59, swatch: "#FFD6E0", shape: "circle" },
        { id: "vs-tote", name: "Pink Striped Tote", slot: "bag", price: 45, swatch: "#FFC0CB", shape: "square" },
        { id: "vs-mist", name: "Bare Vanilla Mist", slot: "accessory", price: 22, swatch: "#FFF0F5", shape: "circle" },
      ],
    },
    {
      id: "coach",
      name: "Coach",
      floor: 3,
      fancy: true,
      color: "#5C4033",
      blurb: "Polished leather with soft everyday glam.",
      cashier: "Coach counter — I’ll wrap these beautifully.",
      items: [
        { id: "coa-tabby", name: "Tabby Shoulder Bag", slot: "bag", price: 450, swatch: "#C9A9A6", shape: "square" },
        { id: "coa-scarf", name: "Signature Scarf", slot: "accessory", price: 95, swatch: "#E6C7B0", shape: "diamond" },
        { id: "coa-loafers", name: "Leather Loafers", slot: "shoes", price: 220, swatch: "#8B5A2B", shape: "circle" },
        { id: "coa-card", name: "Card Case", slot: "accessory", price: 75, swatch: "#F5D0C5", shape: "square" },
      ],
    },
    {
      id: "mk",
      name: "Michael Kors",
      floor: 3,
      fancy: true,
      color: "#C9A227",
      blurb: "Gold hardware and jet-set shine.",
      cashier: "Michael Kors till — fabulous finds!",
      items: [
        { id: "mk-jetset", name: "Jet Set Tote", slot: "bag", price: 298, swatch: "#F0E0C0", shape: "square" },
        { id: "mk-watch", name: "Parker Watch", slot: "accessory", price: 250, swatch: "#D4AF37", shape: "circle" },
        { id: "mk-heels", name: "Claire Heels", slot: "shoes", price: 150, swatch: "#F5C6CE", shape: "diamond" },
        { id: "mk-dress", name: "Wrap Dress", slot: "top", price: 175, swatch: "#F8E1E7", shape: "square" },
      ],
    },
    {
      id: "rolex",
      name: "Rolex",
      floor: 3,
      fancy: true,
      color: "#006039",
      blurb: "The fanciest sparkle-on-your-wrist destination.",
      cashier: "Welcome. A Rolex deserves a proper presentation.",
      items: [
        { id: "rol-datejust", name: "Datejust Pink Dial", slot: "accessory", price: 10500, swatch: "#F7C7D9", shape: "circle" },
        { id: "rol-daytona", name: "Daytona Steel", slot: "accessory", price: 15500, swatch: "#D9D9D9", shape: "square" },
        { id: "rol-oyster", name: "Oyster Bracelet Shine", slot: "accessory", price: 8900, swatch: "#F0F0F0", shape: "diamond" },
        { id: "rol-case", name: "Green Presentation Case", slot: "bag", price: 250, swatch: "#0B3D2E", shape: "square" },
      ],
    },
  ],

  prize: {
    id: "prize-crown",
    name: "Mall Princess Crown",
    slot: "accessory",
    price: 0,
    swatch: "#FFD700",
    shape: "diamond",
    storeId: "prize",
  },

  inventorySlots: 80,

  cashierLines: [
    "Ooo these are so cute on you!",
    "Want a pretty shopping bag with that?",
    "Infinite wallet? Living the dream.",
    "I’ll fold everything extra carefully.",
    "You have amazing taste!",
  ],
};

// Fix accidental typo if any left in LV color
window.MALL_DATA.stores.forEach((store) => {
  store.items.forEach((item) => {
    if (typeof item.swatch === "string") {
      item.swatch = item.swatch.replace(/\s+/g, "");
    }
  });
});
