window.MALL_DATA = {
  inventorySlots: 80,
  cashierLines: [
    "These look amazing on you.",
    "Want me to fold these into a pretty bag?",
    "Infinite wallet? Perfect — no stress today.",
    "I’ll wrap everything carefully.",
    "You have such great taste!",
  ],
  prize: {
    id: "prize-crown",
    name: "Mall Princess Crown",
    slot: "accessory",
    price: 0,
    swatch: "#FFD700",
    shape: "diamond",
    material: "plated metal + crystal",
    detail: "Awarded for shopping every store.",
    display: "shelf",
  },
  stores: [
    {
      id: "sephora",
      name: "Sephora",
      floor: 1,
      fancy: true,
      color: "#E91E63",
      floorColor: "#fff0f5",
      blurb: "Beauty counters, glass shelving, soft pink light.",
      cashier: "Welcome to Sephora! Ready to check out?",
      items: [
        { id: "sep-1", name: "Rare Beauty Soft Pinch Liquid Blush — Happy", slot: "accessory", price: 23, swatch: "#F28CA8", shape: "circle", material: "liquid cream", detail: "0.25 oz weightless blush", display: "shelf" },
        { id: "sep-2", name: "Laneige Lip Sleeping Mask — Berry", slot: "accessory", price: 24, swatch: "#C23A6B", shape: "circle", material: "balm jar", detail: "20g overnight lip mask", display: "shelf" },
        { id: "sep-3", name: "Dior Backstage Glow Face Palette 001", slot: "accessory", price: 53, swatch: "#F6D5C6", shape: "square", material: "pressed powder", detail: "4-pan highlighter/blush", display: "shelf" },
        { id: "sep-4", name: "Sol de Janeiro Brazilian Crush Cheirosa 68", slot: "accessory", price: 38, swatch: "#F7B6D2", shape: "circle", material: "fragrance mist", detail:  "3.04 oz body mist", display: "shelf" },
        { id: "sep-5", name: "Rare Beauty Perfect Strokes Mascara", slot: "accessory", price: 22, swatch: "#1A1A1A", shape: "square", material: "tube", detail: "volumizing black mascara", display: "shelf" },
        { id: "sep-6", name: "Charlotte Tilbury Pillow Talk Lipstick", slot: "accessory", price: 38, swatch: "#C47A86", shape: "circle", material: "satin bullet", detail: "nude-pink lipstick", display: "shelf" },
        { id: "sep-7", name: "Summer Fridays Lip Butter Balm — Pink Sugar", slot: "accessory", price: 24, swatch: "#F3A8B8", shape: "circle", material: "balm stick", detail: "15g tinted balm", display: "shelf" },
        { id: "sep-8", name: "Glow Recipe Watermelon Glow Niacinamide Dew Drops", slot: "accessory", price: 35, swatch: "#FF8FAB", shape: "diamond", material: "serum bottle", detail: "40ml glow serum", display: "shelf" },
      ],
    },
    {
      id: "chanel",
      name: "Chanel",
      floor: 1,
      fancy: true,
      color: "#111111",
      floorColor: "#f4f1ee",
      blurb: "Black-and-white boutique with tweed and perfume.",
      cashier: "Bonjour. Shall I wrap your Chanel pieces?",
      items: [
        { id: "cha-1", name: "Classic Flap Bag Mini — Black Lambskin", slot: "bag", price: 5800, swatch: "#111111", shape: "square", material: "lambskin + gold hardware", detail: "quilted mini flap", display: "mannequin" },
        { id: "cha-2", name: "Rouge Coco Bloom Lipstick — Living Pink", slot: "accessory", price: 50, swatch: "#C71445", shape: "circle", material: "hydrating lipstick", detail: "3g bullet", display: "shelf" },
        { id: "cha-3", name: "Tweed Jacket — Rose Pale", slot: "top", price: 4200, swatch: "#F2D7E0", shape: "square", material: "wool tweed", detail: "cropped couture jacket", display: "hanger" },
        { id: "cha-4", name: "Two-Tone Slingback Pumps — Beige/Black", slot: "shoes", price: 1100, swatch: "#E8D9C8", shape: "diamond", material: "lambskin", detail: "2.2 inch heel", display: "mannequin" },
        { id: "cha-5", name: "Chance Eau Tendre EDT 50ml", slot: "accessory", price: 120, swatch: "#F7C6D8", shape: "circle", material: "eau de toilette", detail: "floral-fruity scent", display: "shelf" },
        { id: "cha-6", name: "Camellia Brooch — White Resin", slot: "accessory", price: 650, swatch: "#FFFFFF", shape: "diamond", material: "resin + metal", detail: "signature camellia pin", display: "shelf" },
        { id: "cha-7", name: "Wide-Leg Trousers — Ivory Crepe", slot: "bottom", price: 1800, swatch: "#F7F2EA", shape: "square", material: "crepe wool", detail: "high-rise trousers", display: "hanger" },
        { id: "cha-8", name: "Cashmere Cardigan — Soft Pink", slot: "top", price: 2100, swatch: "#F6C9D6", shape: "circle", material: "cashmere", detail: "button-front cardigan", display: "hanger" },
      ],
    },
    {
      id: "dior",
      name: "Dior",
      floor: 1,
      fancy: true,
      color: "#6B0F2B",
      floorColor: "#fff5f8",
      blurb: "Grey carpet, couture rails, beauty counters.",
      cashier: "Welcome to Dior. Let’s make this divine.",
      items: [
        { id: "dio-1", name: "Dior Saddle Bag — Latte Oblique", slot: "bag", price: 3900, swatch: "#C7A27C", shape: "square", material: "jacquard canvas", detail: "mini saddle", display: "mannequin" },
        { id: "dio-2", name: "Rosy Glow Blush — 001 Pink", slot: "accessory", price: 48, swatch: "#FF8FAB", shape: "circle", material: "color-adapting powder", detail: "compact blush", display: "shelf" },
        { id: "dio-3", name: "Bar Jacket Dress — Soft Ivory", slot: "top", price: 3200, swatch: "#F7E7EF", shape: "diamond", material: "wool silk blend", detail: "nipped-waist dress", display: "mannequin" },
        { id: "dio-4", name: "J’Adior Slingback Pump — Technical Canvas", slot: "shoes", price: 990, swatch: "#FFFFFF", shape: "circle", material: "embroidered canvas", detail: "65mm heel", display: "mannequin" },
        { id: "dio-5", name: "Miss Dior Blooming Bouquet 50ml", slot: "accessory", price: 108, swatch: "#F4B8CC", shape: "circle", material: "EDT", detail: "peony bouquet scent", display: "shelf" },
        { id: "dio-6", name: "Oblique Silk Scarf — Pink", slot: "accessory", price: 420, swatch: "#E89BB5", shape: "square", material: "silk twill", detail: "90cm scarf", display: "hanger" },
        { id: "dio-7", name: "Pleated Midi Skirt — Midnight", slot: "bottom", price: 2100, swatch: "#2A1030", shape: "square", material: "silk blend", detail: "knife pleats", display: "hanger" },
        { id: "dio-8", name: "Book Tote Small — Toile de Jouy Reverse", slot: "bag", price: 2800, swatch: "#D9C4A8", shape: "square", material: "embroidered canvas", detail: "structured tote", display: "shelf" },
      ],
    },
    {
      id: "tiffany",
      name: "Tiffany & Co.",
      floor: 1,
      fancy: true,
      color: "#81D8D0",
      floorColor: "#eefbf9",
      blurb: "Robin's-egg cases and bright jewelry lighting.",
      cashier: "Something blue and brilliant today?",
      items: [
        { id: "tif-1", name: "Return to Tiffany Heart Tag Necklace — Sterling", slot: "accessory", price: 425, swatch: "#B8F2EC", shape: "diamond", material: "925 sterling silver", detail: "16 in chain", display: "shelf" },
        { id: "tif-2", name: "Tiffany T Smile Bracelet — Narrow", slot: "accessory", price: 650, swatch: "#9FE7DF", shape: "square", material: "sterling silver", detail: "medium size", display: "shelf" },
        { id: "tif-3", name: "Diamond Stud Earrings 0.40 ct tw", slot: "accessory", price: 1800, swatch: "#FFFFFF", shape: "diamond", material: "platinum + diamonds", detail: "round brilliant", display: "shelf" },
        { id: "tif-4", name: "Tiffany HardWear Link Bracelet", slot: "accessory", price: 950, swatch: "#E8FFFC", shape: "circle", material: "sterling silver", detail: "graduated links", display: "shelf" },
        { id: "tif-5", name: "Paloma Picasso Olive Leaf Ring", slot: "accessory", price: 375, swatch: "#D7F5F1", shape: "circle", material: "sterling silver", detail: "size 6", display: "shelf" },
        { id: "tif-6", name: "Tiffany Blue Leather Mini Pouch", slot: "bag", price: 290, swatch: "#81D8D0", shape: "square", material: "calfskin", detail: "zip pouch", display: "mannequin" },
        { id: "tif-7", name: "Knot Earrings — Yellow Gold", slot: "accessory", price: 2400, swatch: "#E8C872", shape: "diamond", material: "18k gold", detail: "medium knots", display: "shelf" },
        { id: "tif-8", name: "Tiffany Infinity Pendant", slot: "accessory", price: 350, swatch: "#F2FFFD", shape: "circle", material: "sterling silver", detail: "pendant necklace", display: "shelf" },
      ],
    },
    {
      id: "cartier",
      name: "Cartier",
      floor: 1,
      fancy: true,
      color: "#B11226",
      floorColor: "#fff7f7",
      blurb: "Red lacquer cases, velvet trays, quiet luxury.",
      cashier: "A Cartier moment — gift wrap?",
      items: [
        { id: "car-1", name: "Love Bracelet — Yellow Gold Small", slot: "accessory", price: 6900, swatch: "#D4AF37", shape: "circle", material: "18k yellow gold", detail: "screwdriver clasp", display: "shelf" },
        { id: "car-2", name: "Tank Must Watch — Small Model", slot: "accessory", price: 3400, swatch: "#F5E6C8", shape: "square", material: "steel + quartz", detail: "silvered dial", display: "shelf" },
        { id: "car-3", name: "Panthère de Cartier Ring", slot: "accessory", price: 5200, swatch: "#E8C872", shape: "diamond", material: "yellow gold", detail: "tsavorite eyes", display: "shelf" },
        { id: "car-4", name: "Juste un Clou Bracelet — Small", slot: "accessory", price: 4100, swatch: "#C9A227", shape: "square", material: "18k yellow gold", detail: "nail motif", display: "shelf" },
        { id: "car-5", name: "Trinity Ring — Classic", slot: "accessory", price: 1600, swatch: "#E6D3A3", shape: "circle", material: "3-gold rolling bands", detail: "size 52", display: "shelf" },
        { id: "car-6", name: "Santos de Cartier Sunglasses", slot: "accessory", price: 780, swatch: "#2B2B2B", shape: "square", material: "acetate + metal", detail: "square frame", display: "mannequin" },
        { id: "car-7", name: "Double C de Cartier Card Holder", slot: "accessory", price: 420, swatch: "#B11226", shape: "square", material: "calfskin", detail: "burgundy leather", display: "shelf" },
        { id: "car-8", name: "Love Necklace — Yellow Gold", slot: "accessory", price: 2750, swatch: "#D4AF37", shape: "diamond", material: "18k gold", detail: "motif pendant", display: "shelf" },
      ],
    },
    {
      id: "ysl",
      name: "Yves Saint Laurent",
      floor: 1,
      fancy: true,
      color: "#2B0A0A",
      floorColor: "#f8f1f1",
      blurb: "Black lacquer walls and gold YSL lettering.",
      cashier: "YSL counter is ready whenever you are.",
      items: [
        { id: "ysl-1", name: "Lou Camera Bag — Black Grain de Poudre", slot: "bag", price: 1790, swatch: "#4A0E0E", shape: "square", material: "leather", detail: "gold cassandre", display: "mannequin" },
        { id: "ysl-2", name: "Rouge Pur Couture Lipstick — 01 Le Rouge", slot: "accessory", price: 42, swatch: "#8B0000", shape: "circle", material: "satin lipstick", detail: "classic red", display: "shelf" },
        { id: "ysl-3", name: "Le Smoking Blazer — Black Grain de Poudre", slot: "top", price: 2600, swatch: "#1C1C1C", shape: "square", material: "wool", detail: "peak lapel tuxedo jacket", display: "hanger" },
        { id: "ysl-4", name: "Opyum 110 Sandal — Patent Black", slot: "shoes", price: 1290, swatch: "#2A0A0A", shape: "diamond", material: "patent leather", detail: "110mm heel", display: "mannequin" },
        { id: "ysl-5", name: "Cassandre Slim Wallet", slot: "accessory", price: 450, swatch: "#1A1A1A", shape: "square", material: "leather", detail: "bi-fold", display: "shelf" },
        { id: "ysl-6", name: "Libre Eau de Parfum 50ml", slot: "accessory", price: 120, swatch: "#F3E6C8", shape: "circle", material: "EDP", detail: "lavender vanilla", display: "shelf" },
        { id: "ysl-7", name: "High-Rise Cigarette Trouser", slot: "bottom", price: 990, swatch: "#111111", shape: "square", material: "wool blend", detail: "black tailored pant", display: "hanger" },
        { id: "ysl-8", name: "Niki Baby Bag — Vintage Leather", slot: "bag", price: 1890, swatch: "#6B3A2C", shape: "square", material: "crinkled leather", detail: "mini shoulder bag", display: "mannequin" },
      ],
    },
    {
      id: "apple",
      name: "Apple",
      floor: 1,
      fancy: false,
      color: "#A2AAAD",
      floorColor: "#f2f4f6",
      blurb: "Glass tables, light wood, glowing product walls.",
      cashier: "Hi! Ready to check out?",
      items: [
        { id: "app-1", name: "iPhone 16 Silicone Case — Light Pink", slot: "accessory", price: 49, swatch: "#FFB6C1", shape: "square", material: "silicone", detail: "MagSafe compatible", display: "shelf" },
        { id: "app-2", name: "AirPods Max — Pink", slot: "accessory", price: 549, swatch: "#F8C8DC", shape: "circle", material: "aluminum + mesh", detail: "over-ear ANC", display: "mannequin" },
        { id: "app-3", name: "Apple Watch Soft Rose Sport Band", slot: "accessory", price: 49, swatch: "#E8A0BF", shape: "diamond", material: "fluoroelastomer", detail: "45mm band", display: "shelf" },
        { id: "app-4", name: "MagSafe Leather Wallet — Peony", slot: "accessory", price: 59, swatch: "#F5D0E0", shape: "square", material: "leather", detail: "Find My support", display: "shelf" },
        { id: "app-5", name: "USB-C Braided Cable 2m — Pink", slot: "accessory", price: 29, swatch: "#F3A8C4", shape: "circle", material: "braided nylon", detail: "240W cable", display: "shelf" },
        { id: "app-6", name: "Beats Studio Pro — Navy/Rose accents", slot: "accessory", price: 349, swatch: "#4A3F55", shape: "square", material: "on-ear wireless", detail: "ANC headphones", display: "mannequin" },
        { id: "app-7", name: "iPad FineWoven Case — Mulberry", slot: "bag", price: 79, swatch: "#8E4B6A", shape: "square", material: "FineWoven", detail: "folio case", display: "shelf" },
        { id: "app-8", name: "AirTag FineWoven Key Ring — Coral", slot: "accessory", price: 35, swatch: "#FF7F7F", shape: "circle", material: "FineWoven", detail: "keyring holder", display: "shelf" },
      ],
    },
    {
      id: "zara",
      name: "Zara",
      floor: 2,
      fancy: false,
      color: "#111111",
      floorColor: "#f7f3f5",
      blurb: "Long rails, mirror walls, packed hangers.",
      cashier: "Zara till is open — bag these up?",
      items: [
        { id: "zar-1", name: "Satin Effect Blazer — Soft Pink", slot: "top", price: 89.9, swatch: "#F3C4D8", shape: "square", material: "satin weave", detail: "structured shoulders", display: "hanger" },
        { id: "zar-2", name: "Pleated Midi Skirt — Ecru", slot: "bottom", price: 59.9, swatch: "#F5F0E8", shape: "diamond", material: "woven fabric", detail: "elastic waist", display: "hanger" },
        { id: "zar-3", name: "Strappy Heeled Sandals — Light Pink", slot: "shoes", price: 69.9, swatch: "#FFCAD4", shape: "circle", material: "synthetic upper", detail: "stiletto 9cm", display: "mannequin" },
        { id: "zar-4", name: "Mini City Bag — Beige", slot: "bag", price: 49.9, swatch: "#EAD7C4", shape: "square", material: "faux leather", detail: "top handle + strap", display: "mannequin" },
        { id: "zar-5", name: "Bow Knit Top — Pale Rose", slot: "top", price: 39.9, swatch: "#FFDEE9", shape: "circle", material: "fine knit", detail: "cropped bow detail", display: "hanger" },
        { id: "zar-6", name: "Wide-Leg Tailored Trousers — Black", slot: "bottom", price: 59.9, swatch: "#1A1A1A", shape: "square", material: "crepe", detail: "high waist", display: "hanger" },
        { id: "zar-7", name: "Faux Leather Bomber — Chocolate", slot: "top", price: 89.9, swatch: "#5C4033", shape: "square", material: "coated fabric", detail: "zip bomber", display: "hanger" },
        { id: "zar-8", name: "Ballet Flats with Strap — Ballet Pink", slot: "shoes", price: 45.9, swatch: "#F4C2C2", shape: "diamond", material: "split leather", detail: "mary-jane style", display: "mannequin" },
        { id: "zar-9", name: "Linen-Blend Shirt Dress — White", slot: "top", price: 69.9, swatch: "#FFFFFF", shape: "square", material: "linen blend", detail: "belted shirt dress", display: "mannequin" },
        { id: "zar-10", name: "Rhinestone Hoop Earrings", slot: "accessory", price: 19.9, swatch: "#F8E8EF", shape: "circle", material: "metal + crystal", detail: "medium hoops", display: "shelf" },
      ],
    },
    {
      id: "gucci",
      name: "Gucci",
      floor: 2,
      fancy: true,
      color: "#0B6623",
      floorColor: "#f4f7f2",
      blurb: "Green-red web accents and logo displays.",
      cashier: "Gucci boutique checkout — fabulous choice.",
      items: [
        { id: "guc-1", name: "GG Marmont Matelassé Mini Bag", slot: "bag", price: 2500, swatch: "#5C4033", shape: "square", material: "chevron leather", detail: "antique gold hardware", display: "mannequin" },
        { id: "guc-2", name: "GG Embroidered Cotton Hoodie — Pink", slot: "top", price: 1200, swatch: "#F7C6D0", shape: "square", material: "cotton fleece", detail: "oversized fit", display: "hanger" },
        { id: "guc-3", name: "Horsebit Slip-On Sandal", slot: "shoes", price: 650, swatch: "#D8B4A0", shape: "diamond", material: "leather", detail: "flat mule", display: "mannequin" },
        { id: "guc-4", name: "Floral Print Silk Scarf", slot: "accessory", price: 495, swatch: "#FF9EBB", shape: "circle", material: "silk", detail: "90x90 cm", display: "hanger" },
        { id: "guc-5", name: "Ace Sneaker with Bee — White/Pink", slot: "shoes", price: 790, swatch: "#FFFFFF", shape: "circle", material: "leather", detail: "low-top", display: "mannequin" },
        { id: "guc-6", name: "Jackie 1961 Small Shoulder Bag", slot: "bag", price: 2800, swatch: "#2F1B14", shape: "square", material: "leather", detail: "piston closure", display: "mannequin" },
        { id: "guc-7", name: "Wide-Leg GG Canvas Pant", slot: "bottom", price: 980, swatch: "#C9B79C", shape: "square", material: "canvas", detail: "high rise", display: "hanger" },
        { id: "guc-8", name: "Interlocking G Sunglasses", slot: "accessory", price: 480, swatch: "#1A1A1A", shape: "diamond", material: "acetate", detail: "cat-eye", display: "shelf" },
      ],
    },
    {
      id: "lv",
      name: "Louis Vuitton",
      floor: 2,
      fancy: true,
      color: "#8B5E3C",
      floorColor: "#f7f1ea",
      blurb: "Monogram trunks, warm wood, soft spotlighting.",
      cashier: "Welcome to Louis Vuitton. A bag for you?",
      items: [
        { id: "lv-1", name: "Neverfull MM — Monogram Canvas", slot: "bag", price: 2100, swatch: "#C2A67E", shape: "square", material: "coated canvas", detail: "toile interior", display: "mannequin" },
        { id: "lv-2", name: "Speedy Bandoulière 25 — Monogram", slot: "bag", price: 1840, swatch: "#A67C52", shape: "square", material: "coated canvas", detail: "removable strap", display: "mannequin" },
        { id: "lv-3", name: "Silk Bandeau — Pink Monogram", slot: "accessory", price: 250, swatch: "#F4C2C2", shape: "circle", material: "silk", detail: "8cm bandeau", display: "hanger" },
        { id: "lv-4", name: "LV Trainer Sneaker — White/Pink", slot: "shoes", price: 990, swatch: "#FFFFFF", shape: "diamond", material: "calf leather", detail: "chunky sole", display: "mannequin" },
        { id: "lv-5", name: "Multi Pochette Accessoires", slot: "bag", price: 1960, swatch: "#B08968", shape: "square", material: "monogram canvas", detail: "removable pouches", display: "shelf" },
        { id: "lv-6", name: "Capucines BB — Pink", slot: "bag", price: 6100, swatch: "#E8A0B5", shape: "square", material: "taurillon leather", detail: "structured handbag", display: "mannequin" },
        { id: "lv-7", name: "Monogram Denim Jacket", slot: "top", price: 2450, swatch: "#6F8FAF", shape: "square", material: "denim", detail: "button jacket", display: "hanger" },
        { id: "lv-8", name: "Félicie Pochette — Empreinte", slot: "bag", price: 1630, swatch: "#C9A9A6", shape: "square", material: "empreinte leather", detail: "chain strap", display: "shelf" },
      ],
    },
    {
      id: "prada",
      name: "Prada",
      floor: 2,
      fancy: true,
      color: "#000000",
      floorColor: "#f3f3f3",
      blurb: "Minimalist black, nylon icons, clean mirrors.",
      cashier: "Prada desk — elegant selections.",
      items: [
        { id: "pra-1", name: "Re-Edition 2005 Nylon Bag", slot: "bag", price: 1450, swatch: "#222222", shape: "square", material: "Re-Nylon", detail: "shoulder strap", display: "mannequin" },
        { id: "pra-2", name: "Re-Nylon Jacket — Black", slot: "top", price: 1680, swatch: "#1A1A1A", shape: "square", material: "recycled nylon", detail: "triangle logo", display: "hanger" },
        { id: "pra-3", name: "Chocolate Brushed Leather Loafer", slot: "shoes", price: 980, swatch: "#5C4033", shape: "diamond", material: "brushed leather", detail: "penny loafer", display: "mannequin" },
        { id: "pra-4", name: "Pleated Techno Fabric Skirt", slot: "bottom", price: 1200, swatch: "#2C2C2C", shape: "circle", material: "techno fabric", detail: "midi length", display: "hanger" },
        { id: "pra-5", name: "Galleria Saffiano Bag — Small", slot: "bag", price: 3200, swatch: "#F5F0EB", shape: "square", material: "Saffiano leather", detail: "double zip", display: "mannequin" },
        { id: "pra-6", name: "Cashmere Crew Knit — Soft Grey", slot: "top", price: 1100, swatch: "#D9D2D0", shape: "square", material: "cashmere", detail: "fine gauge", display: "hanger" },
        { id: "pra-7", name: "Cloudbust Thunder Sneaker", slot: "shoes", price: 1050, swatch: "#EDEDED", shape: "circle", material: "technical fabric", detail: "chunky runner", display: "mannequin" },
        { id: "pra-8", name: "Symbole Sunglasses", slot: "accessory", price: 480, swatch: "#111111", shape: "diamond", material: "acetate", detail: "geometric frame", display: "shelf" },
      ],
    },
    {
      id: "hermes",
      name: "Hermès",
      floor: 2,
      fancy: true,
      color: "#F37021",
      floorColor: "#fff5ee",
      blurb: "Orange boxes, leather walls, quiet carpet.",
      cashier: "Hermès welcomes you. Orange box ready?",
      items: [
        { id: "her-1", name: "Birkin 30 — Gold Togo", slot: "bag", price: 12000, swatch: "#C68642", shape: "square", material: "togo leather", detail: "palladium hardware", display: "mannequin" },
        { id: "her-2", name: "Carré 90 Silk Scarf — Brides de Gala", slot: "accessory", price: 480, swatch: "#FF8C42", shape: "diamond", material: "silk twill", detail: "90cm square", display: "hanger" },
        { id: "her-3", name: "Clic H Bracelet — Rose Dragée", slot: "accessory", price: 740, swatch: "#F7D6E0", shape: "circle", material: "enamel + gold plate", detail: "size PM", display: "shelf" },
        { id: "her-4", name: "Oran Sandal — Rose Dragee", slot: "shoes", price: 780, swatch: "#E8B4BC", shape: "square", material: "epsom leather", detail: "H-cut sandal", display: "mannequin" },
        { id: "her-5", name: "Kelly Wallet To Go — Rose Sakura", slot: "accessory", price: 3200, swatch: "#F3C1D0", shape: "square", material: "epsom", detail: "long wallet", display: "shelf" },
        { id: "her-6", name: "Cashmere Avalon Blanket — Rose", slot: "accessory", price: 1400, swatch: "#F4C2C2", shape: "square", material: "cashmere wool", detail: "fringed throw", display: "shelf" },
        { id: "her-7", name: "Twilly Silk Pair — Pink", slot: "accessory", price: 260, swatch: "#FFB6C1", shape: "circle", material: "silk", detail: "bag/handle wrap", display: "hanger" },
        { id: "her-8", name: "Picotin Lock 18 — Rose Confetti", slot: "bag", price: 3100, swatch: "#F2A7BA", shape: "square", material: "clemence leather", detail: "bucket tote", display: "mannequin" },
      ],
    },
    {
      id: "balenciaga",
      name: "Balenciaga",
      floor: 2,
      fancy: true,
      color: "#111111",
      floorColor: "#ececec",
      blurb: "Concrete floors, oversized racks, bold lighting.",
      cashier: "Balenciaga checkout. Let’s bag the drama.",
      items: [
        { id: "bal-1", name: "Oversized Hoodie — Washed Pink", slot: "top", price: 950, swatch: "#F5C6D0", shape: "square", material: "cotton fleece", detail: "heavyweight", display: "hanger" },
        { id: "bal-2", name: "Triple S Sneaker — White/Pink", slot: "shoes", price: 995, swatch: "#F0E6EE", shape: "circle", material: "mesh + leather", detail: "triple-layer sole", display: "mannequin" },
        { id: "bal-3", name: "Hourglass Small Handbag — Black", slot: "bag", price: 2250, swatch: "#2B2B2B", shape: "diamond", material: "smooth calfskin", detail: "curved silhouette", display: "mannequin" },
        { id: "bal-4", name: "Logo Cap — White", slot: "accessory", price: 450, swatch: "#FFFFFF", shape: "square", material: "cotton", detail: "embroidered logo", display: "shelf" },
        { id: "bal-5", name: "Cargo Track Pant — Black", slot: "bottom", price: 895, swatch: "#1A1A1A", shape: "square", material: "technical jersey", detail: "tapered cargo", display: "hanger" },
        { id: "bal-6", name: "Le Cagole Shoulder Bag — Pink", slot: "bag", price: 2150, swatch: "#E8A0B8", shape: "square", material: "arena lambskin", detail: "studded", display: "mannequin" },
        { id: "bal-7", name: "BB Icon Sunglasses", slot: "accessory", price: 490, swatch: "#111111", shape: "diamond", material: "acetate", detail: "narrow frame", display: "shelf" },
        { id: "bal-8", name: "Zip-Up Track Jacket — Soft Grey", slot: "top", price: 1100, swatch: "#D8D2D5", shape: "square", material: "jersey", detail: "athletic couture", display: "hanger" },
      ],
    },
    {
      id: "fendi",
      name: "Fendi",
      floor: 2,
      fancy: true,
      color: "#C9A227",
      floorColor: "#faf6ea",
      blurb: "Yellow accents, FF motifs, soft spotlights.",
      cashier: "Ciao! Fendi will wrap your picks.",
      items: [
        { id: "fen-1", name: "Baguette Bag — FF Jacquard", slot: "bag", price: 3200, swatch: "#E8D5A3", shape: "square", material: "jacquard fabric", detail: "magnetic clasp", display: "mannequin" },
        { id: "fen-2", name: "FF Logo Sunglasses", slot: "accessory", price: 490, swatch: "#F5E6C5", shape: "diamond", material: "acetate", detail: "oversized", display: "shelf" },
        { id: "fen-3", name: "FF Logo Knit Top — Soft Pink", slot: "top", price: 980, swatch: "#FFF0F5", shape: "circle", material: "viscose knit", detail: "slim fit", display: "hanger" },
        { id: "fen-4", name: "First Ankle Boot — Black Leather", slot: "shoes", price: 1250, swatch: "#3B2F2F", shape: "square", material: "calfskin", detail: "FF buckle", display: "mannequin" },
        { id: "fen-5", name: "Peekaboo ISeeU Petite", slot: "bag", price: 4500, swatch: "#F0E0C8", shape: "square", material: "nappa leather", detail: "two-tone interior", display: "mannequin" },
        { id: "fen-6", name: "Pleated FF Skirt — Butter", slot: "bottom", price: 1200, swatch: "#F3E5AB", shape: "square", material: "silk blend", detail: "midi pleats", display: "hanger" },
        { id: "fen-7", name: "Fendi Roma Shopper Tote", slot: "bag", price: 2100, swatch: "#E8DCC8", shape: "square", material: "canvas leather", detail: "open tote", display: "shelf" },
        { id: "fen-8", name: "Baguette Hair Clip — Gold", slot: "accessory", price: 390, swatch: "#D4AF37", shape: "circle", material: "metal", detail: "logo clip", display: "shelf" },
      ],
    },
    {
      id: "nike",
      name: "Nike",
      floor: 3,
      fancy: false,
      color: "#111111",
      floorColor: "#f2f2f2",
      blurb: "Sneaker walls, mannequins in matching sets.",
      cashier: "Just do it — boxed up?",
      items: [
        { id: "nik-1", name: "Dunk Low Women's — Pink Foam", slot: "shoes", price: 115, swatch: "#FFB6C1", shape: "circle", material: "leather", detail: "low-top basketball shoe", display: "mannequin" },
        { id: "nik-2", name: "Sportswear Tech Fleece Hoodie — Rose", slot: "top", price: 120, swatch: "#F8D7E5", shape: "square", material: "tech fleece", detail: "full-zip", display: "hanger" },
        { id: "nik-3", name: "Sportswear Club Fleece Shorts", slot: "bottom", price: 45, swatch: "#FFFFFF", shape: "diamond", material: "fleece", detail: "mid rise", display: "hanger" },
        { id: "nik-4", name: "One Training Tote — Pink Foam", slot: "bag", price: 55, swatch: "#FFC0CB", shape: "square", material: "polyester", detail: "gym tote", display: "mannequin" },
        { id: "nik-5", name: "Air Force 1 '07 — White/Pink", slot: "shoes", price: 115, swatch: "#FFF5F8", shape: "circle", material: "leather", detail: "classic AF1", display: "mannequin" },
        { id: "nik-6", name: "Dri-FIT One Luxe Tank", slot: "top", price: 46, swatch: "#F3C1D4", shape: "square", material: "Dri-FIT", detail: "slim tank", display: "hanger" },
        { id: "nik-7", name: "Pro 365 High-Waisted Leggings", slot: "bottom", price: 60, swatch: "#2A2A2A", shape: "square", material: "compression knit", detail: "full length", display: "hanger" },
        { id: "nik-8", name: "Heritage Crossbody Bag", slot: "bag", price: 35, swatch: "#E8A0BF", shape: "square", material: "polyester", detail: "adjustable strap", display: "shelf" },
      ],
    },
    {
      id: "adidas",
      name: "Adidas",
      floor: 3,
      fancy: false,
      color: "#000000",
      floorColor: "#f5f5f5",
      blurb: "Three-stripe rails and sneaker cubes.",
      cashier: "Adidas register — great picks!",
      items: [
        { id: "adi-1", name: "Samba OG — Cloud White/Pink", slot: "shoes", price: 100, swatch: "#F5F5F5", shape: "circle", material: "leather + gum sole", detail: "indoor soccer heritage", display: "mannequin" },
        { id: "adi-2", name: "Adicolor Classics Firebird Track Jacket", slot: "top", price: 90, swatch: "#F3C1D4", shape: "square", material: "tricot", detail: "zip track top", display: "hanger" },
        { id: "adi-3", name: "Adicolor Firebird Track Pants", slot: "bottom", price: 80, swatch: "#2A2A2A", shape: "diamond", material: "tricot", detail: "tapered", display: "hanger" },
        { id: "adi-4", name: "Mini Airliner Bag — Almost Pink", slot: "bag", price: 70, swatch: "#E8B4BC", shape: "square", material: "nylon", detail: "crossbody", display: "mannequin" },
        { id: "adi-5", name: "Gazelle Indoor — Bliss Pink", slot: "shoes", price: 100, swatch: "#F7C9D6", shape: "circle", material: "suede", detail: "low profile", display: "mannequin" },
        { id: "adi-6", name: "Trefoil Hoodie — Light Pink", slot: "top", price: 65, swatch: "#F8D5E1", shape: "square", material: "cotton fleece", detail: "pullover", display: "hanger" },
        { id: "adi-7", name: "3-Stripes Bike Shorts", slot: "bottom", price: 35, swatch: "#111111", shape: "square", material: "stretch jersey", detail: "high waist", display: "hanger" },
        { id: "adi-8", name: "Originals Cap — Soft White", slot: "accessory", price: 28, swatch: "#FFFFFF", shape: "square", material: "cotton twill", detail: "trefoil cap", display: "shelf" },
      ],
    },
    {
      id: "lululemon",
      name: "Lululemon",
      floor: 3,
      fancy: true,
      color: "#D31345",
      floorColor: "#fff5f7",
      blurb: "Soft mirrors, folded stacks, pastel sets.",
      cashier: "Need a bag for your Align vibes?",
      items: [
        { id: "lulu-1", name: "Align High-Rise Pant 25\" — Pink Mist", slot: "bottom", price: 98, swatch: "#F4C2C2", shape: "square", material: "Nulu", detail: "buttery soft legging", display: "hanger" },
        { id: "lulu-2", name: "Define Cropped Jacket — Strawberry Milkshake", slot: "top", price: 128, swatch: "#FFE4EC", shape: "diamond", material: "Luon", detail: "slim zip jacket", display: "hanger" },
        { id: "lulu-3", name: "Everywhere Belt Bag 1L — Pink Pastel", slot: "bag", price: 38, swatch: "#E8A0BF", shape: "circle", material: "nylon", detail: "adjustable belt bag", display: "mannequin" },
        { id: "lulu-4", name: "Scuba Oversized Half-Zip Hoodie", slot: "top", price: 118, swatch: "#F7D6E0", shape: "square", material: "cotton-blend fleece", detail: "relaxed scuba", display: "hanger" },
        { id: "lulu-5", name: "Softstreme High-Rise Pant", slot: "bottom", price: 118, swatch: "#EAD9DE", shape: "square", material: "Softstreme", detail: "wide leg", display: "hanger" },
        { id: "lulu-6", name: "Wunder Train Short 6\" — Black", slot: "bottom", price: 68, swatch: "#1A1A1A", shape: "diamond", material: "Everlux", detail: "training short", display: "hanger" },
        { id: "lulu-7", name: "Free to Be Serene Bra", slot: "top", price: 58, swatch: "#F3B8C8", shape: "circle", material: "Nulu", detail: "light support", display: "mannequin" },
        { id: "lulu-8", name: "Dual Pouch Wristlet — Pink", slot: "accessory", price: 38, swatch: "#F2A7BA", shape: "square", material: "nylon", detail: "two zip pouches", display: "shelf" },
      ],
    },
    {
      id: "vs",
      name: "Victoria's Secret",
      floor: 3,
      fancy: true,
      color: "#6B0F2B",
      floorColor: "#fff0f4",
      blurb: "Pink carpet, perfume haze, soft mannequins.",
      cashier: "Hi angel — ready to check out?",
      items: [
        { id: "vs-1", name: "Satin Short Robe — Soft Rouge", slot: "top", price: 79.5, swatch: "#E8B4BC", shape: "diamond", material: "satin", detail: "tie waist robe", display: "hanger" },
        { id: "vs-2", name: "Faux Feather Slipper — Pink", slot: "shoes", price: 59.5, swatch: "#FFD6E0", shape: "circle", material: "textile + faux feather", detail: "open toe", display: "mannequin" },
        { id: "vs-3", name: "Iconic Stripe Tote — Pink/White", slot: "bag", price: 45, swatch: "#FFC0CB", shape: "square", material: "canvas", detail: "open tote", display: "mannequin" },
        { id: "vs-4", name: "Bare Vanilla Fragrance Mist 250ml", slot: "accessory", price: 22, swatch: "#FFF0F5", shape: "circle", material: "body mist", detail: "vanilla musk", display: "shelf" },
        { id: "vs-5", name: "Cotton Logo Short Set — Pink", slot: "bottom", price: 49.5, swatch: "#F7C9D6", shape: "square", material: "cotton jersey", detail: "sleep short", display: "hanger" },
        { id: "vs-6", name: "Bombshell Eau de Parfum 50ml", slot: "accessory", price: 72, swatch: "#F4A7C2", shape: "circle", material: "EDP", detail: "fruity floral", display: "shelf" },
        { id: "vs-7", name: "Cozy Knit Cardigan — Cream Pink", slot: "top", price: 69.5, swatch: "#F8E1E7", shape: "square", material: "chenille knit", detail: "open cardigan", display: "hanger" },
        { id: "vs-8", name: "Velvet Scrunchie Set", slot: "accessory", price: 12.5, swatch: "#C97B9A", shape: "circle", material: "velvet", detail: "3-pack", display: "shelf" },
      ],
    },
    {
      id: "coach",
      name: "Coach",
      floor: 3,
      fancy: true,
      color: "#5C4033",
      floorColor: "#f7f1ec",
      blurb: "Leather walls, brass hardware, soft lighting.",
      cashier: "Coach counter — I’ll wrap these beautifully.",
      items: [
        { id: "coa-1", name: "Tabby Shoulder Bag 26 — Soft Rose", slot: "bag", price: 450, swatch: "#C9A9A6", shape: "square", material: "glovetanned leather", detail: "magnetic flap", display: "mannequin" },
        { id: "coa-2", name: "Signature Silk Square Scarf", slot: "accessory", price: 95, swatch: "#E6C7B0", shape: "diamond", material: "silk", detail: "C signature print", display: "hanger" },
        { id: "coa-3", name: "Léa Loafer — Dark Stone", slot: "shoes", price: 220, swatch: "#8B5A2B", shape: "circle", material: "leather", detail: "stacked heel", display: "mannequin" },
        { id: "coa-4", name: "Essential Card Case — Pink", slot: "accessory", price: 75, swatch: "#F5D0C5", shape: "square", material: "crossgrain leather", detail: "snap case", display: "shelf" },
        { id: "coa-5", name: "Willow Tote Bag — Chalk", slot: "bag", price: 395, swatch: "#F3ECE4", shape: "square", material: "pebbled leather", detail: "open tote", display: "mannequin" },
        { id: "coa-6", name: "Quilted Jacket — Soft Black", slot: "top", price: 450, swatch: "#2A2A2A", shape: "square", material: "nylon fill", detail: "lightweight quilt", display: "hanger" },
        { id: "coa-7", name: "CitySole Court Sneaker", slot: "shoes", price: 160, swatch: "#F7F2EF", shape: "circle", material: "leather", detail: "low court shoe", display: "mannequin" },
        { id: "coa-8", name: "Chain Tabby Clutch", slot: "bag", price: 295, swatch: "#E8B4BC", shape: "square", material: "leather", detail: "chain strap", display: "shelf" },
      ],
    },
    {
      id: "mk",
      name: "Michael Kors",
      floor: 3,
      fancy: true,
      color: "#C9A227",
      floorColor: "#faf6ea",
      blurb: "Gold hardware sparkle and jet-set displays.",
      cashier: "Michael Kors till — fabulous finds!",
      items: [
        { id: "mk-1", name: "Jet Set Travel Top-Zip Tote — Soft Pink", slot: "bag", price: 298, swatch: "#F0E0C0", shape: "square", material: "saffiano leather", detail: "top zip tote", display: "mannequin" },
        { id: "mk-2", name: "Parker Pavé Watch — Rose Gold Tone", slot: "accessory", price: 250, swatch: "#D4AF37", shape: "circle", material: "stainless steel", detail: "crystal bezel", display: "shelf" },
        { id: "mk-3", name: "Claire Flex Pump — Soft Pink", slot: "shoes", price: 150, swatch: "#F5C6CE", shape: "diamond", material: "leather", detail: "flex sole heel", display: "mannequin" },
        { id: "mk-4", name: "Hardware Wrap Dress — Blush", slot: "top", price: 175, swatch: "#F8E1E7", shape: "square", material: "stretch jersey", detail: "gold logo hardware", display: "mannequin" },
        { id: "mk-5", name: "Mercer Medium Messenger", slot: "bag", price: 328, swatch: "#E8C8B0", shape: "square", material: "crossgrain leather", detail: "flap messenger", display: "mannequin" },
        { id: "mk-6", name: "Logo Legging — Black/Gold", slot: "bottom", price: 98, swatch: "#1A1A1A", shape: "square", material: "stretch knit", detail: "high waist", display: "hanger" },
        { id: "mk-7", name: "Britton Logo Sneaker", slot: "shoes", price: 130, swatch: "#FFFFFF", shape: "circle", material: "mixed media", detail: "chunky sneaker", display: "mannequin" },
        { id: "mk-8", name: "Carmen Large Pouchette", slot: "accessory", price: 128, swatch: "#F2C1CF", shape: "square", material: "saffiano", detail: "wristlet", display: "shelf" },
      ],
    },
    {
      id: "rolex",
      name: "Rolex",
      floor: 3,
      fancy: true,
      color: "#006039",
      floorColor: "#eef6f1",
      blurb: "Glass vitrines, green carpets, quiet luxury.",
      cashier: "Welcome. A Rolex deserves a proper presentation.",
      items: [
        { id: "rol-1", name: "Datejust 31 — Pink Dial Jubilee", slot: "accessory", price: 10500, swatch: "#F7C7D9", shape: "circle", material: "Oystersteel + Everose", detail: "automatic", display: "shelf" },
        { id: "rol-2", name: "Cosmograph Daytona — White Dial", slot: "accessory", price: 15500, swatch: "#D9D9D9", shape: "square", material: "Oystersteel", detail: "chronograph", display: "shelf" },
        { id: "rol-3", name: "Oyster Perpetual 36 — Candy Pink", slot: "accessory", price: 8900, swatch: "#F4A7C0", shape: "diamond", material: "Oystersteel", detail: "bright dial", display: "shelf" },
        { id: "rol-4", name: "Green Leather Presentation Case", slot: "bag", price: 250, swatch: "#0B3D2E", shape: "square", material: "leatherette", detail: "watch box", display: "shelf" },
        { id: "rol-5", name: "Datejust Fluted Bezel — Silver Dial", slot: "accessory", price: 11200, swatch: "#F0F0F0", shape: "circle", material: "Oystersteel + white gold", detail: "31mm", display: "shelf" },
        { id: "rol-6", name: "Pearlmaster Pearl Bracelet Look Book Clutch", slot: "bag", price: 480, swatch: "#F5E6EE", shape: "square", material: "satin", detail: "display clutch", display: "mannequin" },
        { id: "rol-7", name: "Rolex Green Cap", slot: "accessory", price: 120, swatch: "#006039", shape: "square", material: "cotton", detail: "crown logo", display: "shelf" },
        { id: "rol-8", name: "Oyster Bracelet Polish Cloth Set", slot: "accessory", price: 45, swatch: "#E8EEE9", shape: "circle", material: "microfiber", detail: "care kit", display: "shelf" },
      ],
    },
  ],
};
